title: "ORPS - Outcome-Refining Process Supervision"
description: "Reasoning Through Execution: Unifying Process and Outcome Rewards for Code Generation"
url: "https://zhuohaoyu.github.io"
baseurl: "/ORPS"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  authors:
    output: false

# Exclude files
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md

# Social links
github_username: zhuohaoyu
paper_url: "https://arxiv.org/abs/2506.03637"
github_repo: "https://github.com/zhuohaoyu/ORPS"
pypi_url: "https://pypi.org/project/orps/"

# Project info
version: "1.0.0"
license: "MIT"
conference: "ICML 2025"

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  syntax_highlighter: rouge 